WebSanbox/Controllers/RoleAdminController.cs
namespace WebSanbox.Controllers
{
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    using ThinkEco.Identity.Data.Models;

    using WebSanbox.Models;

    [Authorize(Roles = "Administrators")]
    public class RoleAdminController : BaseController
    {
        // GET: RoleAdmin
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<ActionResult> Create([Required] string name)
        {
            if (!ModelState.IsValid)
            {
                return this.View(name);
            }

            var result = await RoleManager.CreateAsync(new ApplicationRole(name));
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            this.AddErrorsFromResult(result);
            return this.View(name);
        }

        public async Task<ActionResult> Edit([Required] string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            var memberIds = role.Users.Select(x => x.UserId).ToArray();

            var members = UserManager.Users.Where(x => memberIds.Any(y => y == x.Id));
            var nonmembers = UserManager.Users.Except(members);

            return this.View(new RoleEditModel { Members = members, NonMembers = nonmembers, Role = role });
        }

        [HttpPost]
        public async Task<ActionResult> Edit(RoleModificationModel model)
        {
            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            var role = await RoleManager.FindByNameAsync(model.RoleName);
            if (role == null)
            {
                return this.View("Error", new[] { "Role not found" });
            }

            foreach (var user in model.IdsToAdd ?? new string[]{})
            {
                var result = await UserManager.AddToRoleAsync(user, role.Name);
                if (!result.Succeeded)
                {
                    return this.View(result.Errors);
                }
            }

            foreach (var user in model.IdsToDelete ?? new string[]{})
            {
                var result = await UserManager.RemoveFromRoleAsync(user, role.Name);
                if (!result.Succeeded)
                {
                    return this.View(result.Errors);
                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete([Required] string id)
        {
            var role = RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return this.View("Error", new[] { "Role name not found" });
            }

            var result = await RoleManager.DeleteAsync(role.Result);
            if (!result.Succeeded)
            {
                this.AddErrorsFromResult(result);
                return this.View("Error", result.Errors);
            }

            return RedirectToAction("Index");
        }
    }
}

WebSanbox/Views/RoleAdmin/Create.cshtml
@model string
@{ ViewBag.Title = "Create Role";}
<h2> Create Role </h2> @Html.ValidationSummary(false)
@using (Html.BeginForm())
{
    <div class="form-group">
        <label> Name </label> <input name="name" value="@Model" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary"> Create </button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

WebSanbox/Views/RoleAdmin/Edit.cshtml
@using ThinkEco.Identity.Data.Models
@model WebSanbox.Models.RoleEditModel
@{ ViewBag.Title = "Edit Role";}
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <div class=" panel panel-primary">
        <div class=" panel-heading"> Add To @Model.Role.Name </div>
        <table class="table table-striped">
            @if (!Model.NonMembers.Any())
            {
                <tr> <td colspan=" 2"> All Users Are Members </td> </tr>
            }
            else
            {
                <tr> <td> User ID </td> <td> Add To Role </td> </tr>
                foreach (ApplicationUser user in Model.NonMembers)
                {
                    <tr>
                        <td>@user.UserName </td>
                        <td> <input type="checkbox" name="IdsToAdd" value="@user.Id"> </td>
                    </tr>
                }
            }
        </table>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading"> Remove from @Model.Role.Name</div>
        <table class="table table-striped">
            @if (!Model.Members.Any())
            {
                <tr> <td colspan="2"> No Users Are Members </td> </tr>
            }
            else
            {
                <tr>
                    <td> User ID </td>
                    <td> Remove From Role </td>
                </tr>
                foreach (ApplicationUser user in Model.Members)
                {
                    <tr> <td>@user.UserName </td> <td> <input type="checkbox" name="IdsToDelete" value="@user.Id"> </td> </tr>
                }
            }
        </table>
    </div>
    <button type="submit" class=" btn btn-primary"> Save </button>
    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-default" })
}

WebSanbox/Views/RoleAdmin/Index.cshtml
@using Jerboa.Identity.Data.Models
@using WebSanbox.Helpers
@model IEnumerable<ApplicationRole>
@{ ViewBag.Title = "Roles"; }
<div class="panel panel-primary">
    <div class="panel-heading">Roles</div>
    <table class="table table-striped">
        <tr>
            <th> ID </th>
            <th> Name </th>
            <th> Users </th>
            <th> </th>
        </tr>
        @if (!Model.Any())
        {
            <tr>
                <td colspan="4" class="text-center"> No Roles </td>
            </tr>
        }
        else
        {
            foreach (ApplicationRole role in Model)
            {
            <tr>
                <td>
                    @role.Id
                </td>
                <td>
                    @role.Name
                </td>
                <td>
                    @if (role.Users == null || !role.Users.Any())
                    {
                        @: No Users in Role
    }
                    else
                    {
                        <p>@string.Join(", ", role.Users.Select(x => Html.GetUserName(x.UserId))) </p>
                    }
                </td>
                <td>
                    @using (Html.BeginForm("Delete", "RoleAdmin", new { id = role.Id }))
                    { @Html.ActionLink("Edit", "Edit", new { id = role.Id }, new { @class = "btn btn-primary btn-xs" }) <button class="btn btn-danger btn-xs" type="submit"> Delete </button> }
                </td>
            </tr> }
        }
    </table>
</div> @Html.ActionLink("Create", "Create", null, new { @class = "btn btn-primary" })